### ISSUE TITLE
iemocap_cat-word2vec.py line 73 EOFError: unexpected end of input; is count incorrect or file otherwise damaged?

### ISSUE THREAD

**Issue by FriedaSmith** [bagustris/isst_2019#1]
Hello. When I run your code `iemocap_cat-word2vec.py` in line 73  `word_vectors = KeyedVectors.load_word2vec_format(file_loc, binary=True)`, it had an exception:

```
models/GoogleNews-vectors-negative300.bin
Traceback (most recent call last):
  File "/media/other/Code/SER/bt/isst_2019/iemocap_cat-word2vec.py", line 73, in <module>
    word_vectors = KeyedVectors.load_word2vec_format(file_loc, binary=True)
  File "/home/chen/.local/lib/python3.7/site-packages/gensim/models/keyedvectors.py", line 1549, in load_word2vec_format
    limit=limit, datatype=datatype)
  File "/home/chen/.local/lib/python3.7/site-packages/gensim/models/utils_any2vec.py", line 286, in _load_word2vec_format
    vocab_size, vector_size, datatype, unicode_errors, binary_chunk_size)
  File "/home/chen/.local/lib/python3.7/site-packages/gensim/models/utils_any2vec.py", line 210, in _word2vec_read_binary
    raise EOFError("unexpected end of input; is count incorrect or file otherwise damaged?")
EOFError: unexpected end of input; is count incorrect or file otherwise damaged?
```

 I'm so confused, plz help me!!!!

**Comment by bagustris** [comment]
Two cues for me, 

First, maybe the culprit is the python, my python version is 3.6 (actually 3.6.12).  
Second, the gensim version, I used gensim 3.8.3.

Check these versions.

**Comment by FriedaSmith** [comment]
It may have problems with the python version. My python version is 3.7.5 and gensim is also 3.8.3

**Comment by FriedaSmith** [comment]
It's strange. I rerun the code and it works.
